### ISSUE TITLE
Word "Speakers" instead "Monkeys" in README.md

### ISSUE THREAD

**Issue by 4cruzeta** [jamesmontemagno/MonkeysApp-Workshop#4]
Sometimes the word Speakers appears in the README.md instead of Monkeys. 
I got confused with it. 
Ohh !!! We rookies... :)
Hope it can help someone.
Great Job Montemagno !!!
Thanks for share it.

**Comment by jamesmontemagno** [comment]
I have a new version here: https://github.com/jamesmontemagno/xamarin.forms-workshop
